apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"europe-north1.svc.cluster.local": ["10.126.0.8"], "europe-west1.svc.cluster.local": ["10.127.0.8"]}
