apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"europe-west1.svc.cluster.local": ["10.127.0.8"], "europe-central2.svc.cluster.local": ["10.128.0.8"]}
