---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: modrule-cockroachdb-europe-west1-b
spec:
  type: Patch

  match:
    - select: '$.kind'
      matchValue: Pod

    - select: '$.metadata.labels.app'
      matchValue: 'cockroachdb'

    - select: '$.metadata.name'
      matchValue: 'cockroachdb-0'

    - select: '$.metadata.namespace'
      matchValue: 'europe-west1'

  patch:
    - op: add
      path: /metadata/labels/zone
      value: 'europe-west1-b'
    - op: add
      path: /spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution
      value: |-
        nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - 'europe-west1-b'
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: modrule-cockroachdb-europe-west1-c
spec:
  type: Patch

  match:
    - select: '$.kind'
      matchValue: Pod

    - select: '$.metadata.labels.app'
      matchValue: 'cockroachdb'

    - select: '$.metadata.name'
      matchValue: 'cockroachdb-1'

    - select: '$.metadata.namespace'
      matchValue: 'europe-west1'

  patch:
    - op: add
      path: /metadata/labels/zone
      value: 'europe-west1-c'
    - op: add
      path: /spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution
      value: |-
        nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - 'europe-west1-c'
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: modrule-cockroachdb-europe-west1-d
spec:
  type: Patch

  match:
    - select: '$.kind'
      matchValue: Pod

    - select: '$.metadata.labels.app'
      matchValue: 'cockroachdb'

    - select: '$.metadata.name'
      matchValue: 'cockroachdb-2'

    - select: '$.metadata.namespace'
      matchValue: 'europe-west1'

  patch:
    - op: add
      path: /metadata/labels/zone
      value: 'europe-west1-d'
    - op: add
      path: /spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution
      value: |-
        nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - 'europe-west1-d'
